### ISSUE TITLE
Unable to open superpixel_fcn folder

### ISSUE THREAD

**Issue by iA-oO** [lyumingzhi/AWD-AGP#1]
Hello,

I encountered an issue with the `superpixel_fcn` folder in this repository.

I found a solution to this problem online. Here is the link to the solution for reference: https://clay-atlas.com/blog/2023/05/08/solved-github-cannot-check-arrow-folder/.

Could you please fix this issue so that the contents of the `superpixel_fcn` folder can be accessed?

Thank you!

**Comment by Hallucinatie** [comment]
The submodule is apparently not set properly. Hope the author can fix asap.
